package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_SIGNAL extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SIGNAL() {
    super(0x99409c00ced4933L, 0xb9e3928d0c704016L, 0x110dd9137bf9a37L, "SIGNAL", "r:7bfc2ac3-4866-4488-b53e-56494783dd09(ArduinoML.structure)/76804809440598583", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_HIGH_0 = new EnumerationDescriptor.MemberDescriptor("HIGH", "high", "r:7bfc2ac3-4866-4488-b53e-56494783dd09(ArduinoML.structure)/76804809440598584", "HIGH");
  private final EnumerationDescriptor.MemberDescriptor VALUE_LOW_0 = new EnumerationDescriptor.MemberDescriptor("LOW", "low", "r:7bfc2ac3-4866-4488-b53e-56494783dd09(ArduinoML.structure)/76804809440598585", "LOW");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return VALUE_HIGH_0;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_HIGH_0, VALUE_LOW_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "HIGH":
        return VALUE_HIGH_0;
      case "LOW":
        return VALUE_LOW_0;
    }
    return null;
  }
}
