package ArduinoML.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import java.util.Arrays;

public class EnumerationDescriptor_SOUND extends EnumerationDescriptorBase {

  public EnumerationDescriptor_SOUND() {
    super(0x99409c00ced4933L, 0xb9e3928d0c704016L, 0x763d497ee8ea3823L, "SOUND", "r:7bfc2ac3-4866-4488-b53e-56494783dd09(ArduinoML.structure)/8520046879477217315", PrimitiveTypeId.STRING);
  }

  private final EnumerationDescriptor.MemberDescriptor VALUE_shortBeep_0 = new EnumerationDescriptor.MemberDescriptor("shortBeep();", "short", "r:7bfc2ac3-4866-4488-b53e-56494783dd09(ArduinoML.structure)/8520046879477217326", "shortBeep();");
  private final EnumerationDescriptor.MemberDescriptor VALUE_longBeep_0 = new EnumerationDescriptor.MemberDescriptor("longBeep();", "long", "r:7bfc2ac3-4866-4488-b53e-56494783dd09(ArduinoML.structure)/8520046879477217316", "longBeep();");

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public Collection<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return Arrays.asList(VALUE_shortBeep_0, VALUE_longBeep_0);
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String string) {
    if (string == null) {
      return null;
    }
    switch (string) {
      case "shortBeep();":
        return VALUE_shortBeep_0;
      case "longBeep();":
        return VALUE_longBeep_0;
    }
    return null;
  }
}
